import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';

export default function Index() {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div>
      <Head>
        <title>Blog {id}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Blog {id}</h1>
    </div>
  );
}
