import Head from 'next/head';
import React from 'react';

export default function Index() {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>About</h1>
    </div>
  );
}
